export {
    BadRequestException,
    BadGatewayException,
    GatewayTimeoutException,
    HttpException,
    ConflictException,
    ForbiddenException,
    GoneException,
    ImATeapotException,
    HttpVersionNotSupportedException,
    NotAcceptableException,
    NotFoundException,
    NotImplementedException,
    RequestTimeoutException,
    MethodNotAllowedException,
    PayloadTooLargeException,
    PreconditionFailedException,
    UnauthorizedException,
    ServiceUnavailableException,
    InternalServerErrorException,
    UnprocessableEntityException,
    UnsupportedMediaTypeException,
    ResourceNotFoundException,
} from './default.exception';
